"""empty message

Revision ID: 524d239acb25
Revises: 9af6e5897e10
Create Date: 2018-12-25 02:26:18.376573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524d239acb25'
down_revision = '9af6e5897e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
